name: mlmb-model-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pip
  - scikit-learn
  - ipykernel
  - pandas
  - pip:
      - azureml-inference-server-http
      - inference-schema
      - joblib
