import { ITeam } from "../common/models";

export const teams: ITeam[] = [
  {
    School: "Abilene Christian",
    "City, State": "Abilene, Texas",
    "SR key": "abilene-christian",
    "NCAA key": "abilene-christian",
    "NCAA School": "Abilene Christian",
    "NCAA Name": "Abilene Christian University",
    "background-color": "#582C83",
  },
  {
    School: "Air Force",
    "City, State": "USAF Academy, Colorado",
    "SR key": "air-force",
    "NCAA key": "air-force",
    "NCAA School": "Air Force",
    "NCAA Name": "Air Force Academy",
    "background-color": "#0032A0",
  },
  {
    School: "Akron",
    "City, State": "Akron, Ohio",
    "SR key": "akron",
    "NCAA key": "akron",
    "NCAA School": "Akron",
    "NCAA Name": "University of Akron",
    "background-color": "#0F192B",
  },
  {
    School: "Alabama",
    "City, State": "Tuscaloosa, Alabama",
    "SR key": "alabama",
    "NCAA key": "alabama",
    "NCAA School": "Alabama",
    "NCAA Name": "University of Alabama",
    "background-color": "#9D2235",
  },
  {
    School: "Alabama A&M",
    "City, State": "Normal, Alabama",
    "SR key": "alabama-am",
    "NCAA key": "alabama-am",
    "NCAA School": "Alabama A&M",
    "NCAA Name": "Alabama A&M University",
    "background-color": "#862633",
  },
  {
    School: "Alabama State",
    "City, State": "Montgomery, Alabama",
    "SR key": "alabama-state",
    "NCAA key": "alabama-st",
    "NCAA School": "Alabama St.",
    "NCAA Name": "Alabama State University",
    "background-color": "#010101",
  },
  {
    School: "Albany (NY)",
    "City, State": "Albany, New York",
    "SR key": "albany-ny",
    "NCAA key": "albany-ny",
    "NCAA School": "Albany (NY)",
    "NCAA Name": "University at Albany",
    "background-color": "#46166B",
  },
  {
    School: "Alcorn State",
    "City, State": "Alcorn State, Mississippi",
    "SR key": "alcorn-state",
    "NCAA key": "alcorn",
    "NCAA School": "Alcorn St.",
    "NCAA Name": "Alcorn State University",
    "background-color": "#512D6D",
  },
  {
    School: "American",
    "City, State": "Washington, D.C.",
    "SR key": "american",
    "NCAA key": "american",
    "NCAA School": "American",
    "NCAA Name": "American University",
    "background-color": "#A6192E",
  },
  {
    School: "Appalachian State",
    "City, State": "Boone, North Carolina",
    "SR key": "appalachian-state",
    "NCAA key": "appalachian-st",
    "NCAA School": "Appalachian St.",
    "NCAA Name": "Appalachian State University",
    "background-color": "#010101",
  },
  {
    School: "Arizona",
    "City, State": "Tucson, Arizona",
    "SR key": "arizona",
    "NCAA key": "arizona",
    "NCAA School": "Arizona",
    "NCAA Name": "University of Arizona",
    "background-color": "#00205B",
  },
  {
    School: "Arizona State",
    "City, State": "Tempe, Arizona",
    "SR key": "arizona-state",
    "NCAA key": "arizona-st",
    "NCAA School": "Arizona St.",
    "NCAA Name": "Arizona State University",
    "background-color": "#8A0C3C",
  },
  {
    School: "Arkansas",
    "City, State": "Fayetteville, Arkansas",
    "SR key": "arkansas",
    "NCAA key": "arkansas",
    "NCAA School": "Arkansas",
    "NCAA Name": "University of Arkansas",
    "background-color": "#9D2235",
  },
  {
    School: "Arkansas State",
    "City, State": "State University, Arkansas",
    "SR key": "arkansas-state",
    "NCAA key": "arkansas-st",
    "NCAA School": "Arkansas St.",
    "NCAA Name": "Arkansas State University",
    "background-color": "#C8102E",
  },
  {
    School: "Arkansas-Pine Bluff",
    "City, State": "Pine Bluff, Arkansas",
    "SR key": "arkansas-pine-bluff",
    "NCAA key": "ark-pine-bluff",
    "NCAA School": "Ark.-Pine Bluff",
    "NCAA Name": "University of Arkansas-Pine Bluff",
    "background-color": "#010101",
  },
  {
    School: "Army",
    "City, State": "West Point, New York",
    "SR key": "army",
    "NCAA key": "army",
    "NCAA School": "Army",
    "NCAA Name": "Army West Point",
    "background-color": "#010101",
  },
  {
    School: "Auburn",
    "City, State": "Auburn, Alabama",
    "SR key": "auburn",
    "NCAA key": "auburn",
    "NCAA School": "Auburn",
    "NCAA Name": "Auburn University",
    "background-color": "#FA4616",
  },
  {
    School: "Austin Peay",
    "City, State": "Clarksville, Tennessee",
    "SR key": "austin-peay",
    "NCAA key": "austin-peay",
    "NCAA School": "Austin Peay",
    "NCAA Name": "Austin Peay State University",
    "background-color": "#BA0C2F",
  },
  {
    School: "Ball State",
    "City, State": "Muncie, Indiana",
    "SR key": "ball-state",
    "NCAA key": "ball-st",
    "NCAA School": "Ball St.",
    "NCAA Name": "Ball State University",
    "background-color": "#BA0C2F",
  },
  {
    School: "Baylor",
    "City, State": "Waco, Texas",
    "SR key": "baylor",
    "NCAA key": "baylor",
    "NCAA School": "Baylor",
    "NCAA Name": "Baylor University",
    "background-color": "#1B3E30",
  },
  {
    School: "Bellarmine",
    "City, State": "Louisville, Kentucky",
    "SR key": "bellarmine",
    "NCAA key": "bellarmine",
    "NCAA School": "Bellarmine",
    "NCAA Name": "Bellarmine University",
    "background-color": "#772f40",
  },
  {
    School: "Belmont",
    "City, State": "Nashville, Tennessee",
    "SR key": "belmont",
    "NCAA key": "belmont",
    "NCAA School": "Belmont",
    "NCAA Name": "Belmont University",
    "background-color": "#0D2C6B",
  },
  {
    School: "Bethune-Cookman",
    "City, State": "Daytona Beach, Florida",
    "SR key": "bethune-cookman",
    "NCAA key": "bethune-cookman",
    "NCAA School": "Bethune-Cookman",
    "NCAA Name": "Bethune-Cookman University",
    "background-color": "#6F263D",
  },
  {
    School: "Binghamton",
    "City, State": "Binghamton, New York",
    "SR key": "binghamton",
    "NCAA key": "binghamton",
    "NCAA School": "Binghamton",
    "NCAA Name": "Binghamton University",
    "background-color": "#006747",
  },
  {
    School: "Boise State",
    "City, State": "Boise, Idaho",
    "SR key": "boise-state",
    "NCAA key": "boise-st",
    "NCAA School": "Boise St.",
    "NCAA Name": "Boise State University",
    "background-color": "#0032A0",
  },
  {
    School: "Boston College",
    "City, State": "Chestnut Hill, Massachusetts",
    "SR key": "boston-college",
    "NCAA key": "boston-college",
    "NCAA School": "Boston College",
    "NCAA Name": "Boston College",
    "background-color": "#862633",
  },
  {
    School: "Boston University",
    "City, State": "Boston, Massachusetts",
    "SR key": "boston-university",
    "NCAA key": "boston-u",
    "NCAA School": "Boston U.",
    "NCAA Name": "Boston University",
    "background-color": "#C8102E",
  },
  {
    School: "Bowling Green State",
    "City, State": "Bowling Green, Ohio",
    "SR key": "bowling-green-state",
    "NCAA key": "bowling-green",
    "NCAA School": "Bowling Green",
    "NCAA Name": "Bowling Green State University",
    "background-color": "#FE5000",
  },
  {
    School: "Bradley",
    "City, State": "Peoria, Illinois",
    "SR key": "bradley",
    "NCAA key": "bradley",
    "NCAA School": "Bradley",
    "NCAA Name": "Bradley University",
    "background-color": "#A21B21",
  },
  {
    School: "Brigham Young",
    "City, State": "Provo, Utah",
    "SR key": "brigham-young",
    "NCAA key": "byu",
    "NCAA School": "BYU",
    "NCAA Name": "Brigham Young University",
    "background-color": "#213C84",
  },
  {
    School: "Brown",
    "City, State": "Providence, Rhode Island",
    "SR key": "brown",
    "NCAA key": "brown",
    "NCAA School": "Brown",
    "NCAA Name": "Brown University",
    "background-color": "#4E3629",
  },
  {
    School: "Bryant",
    "City, State": "Smithfield, Rhode Island",
    "SR key": "bryant",
    "NCAA key": "bryant",
    "NCAA School": "Bryant",
    "NCAA Name": "Bryant University",
    "background-color": "#010101",
  },
  {
    School: "Bucknell",
    "City, State": "Lewisburg, Pennsylvania",
    "SR key": "bucknell",
    "NCAA key": "bucknell",
    "NCAA School": "Bucknell",
    "NCAA Name": "Bucknell University",
    "background-color": "#071D49",
  },
  {
    School: "Buffalo",
    "City, State": "Buffalo, New York",
    "SR key": "buffalo",
    "NCAA key": "buffalo",
    "NCAA School": "Buffalo",
    "NCAA Name": "University at Buffalo",
    "background-color": "#0057B8",
  },
  {
    School: "Butler",
    "City, State": "Indianapolis, Indiana",
    "SR key": "butler",
    "NCAA key": "butler",
    "NCAA School": "Butler",
    "NCAA Name": "Butler University",
    "background-color": "#13294B",
  },
  {
    School: "Cal Poly",
    "City, State": "San Luis Obispo, California",
    "SR key": "cal-poly",
    "NCAA key": "cal-poly",
    "NCAA School": "Cal Poly",
    "NCAA Name": "Cal Poly",
    "background-color": "#193E30",
  },
  {
    School: "Cal State Bakersfield",
    "City, State": "Bakersfield, California",
    "SR key": "cal-state-bakersfield",
    "NCAA key": "bakersfield",
    "NCAA School": "CSU Bakersfield",
    "NCAA Name": "CSU Bakersfield",
    "background-color": "#0032A0",
  },
  {
    School: "Cal State Fullerton",
    "City, State": "Fullerton, California",
    "SR key": "cal-state-fullerton",
    "NCAA key": "cal-st-fullerton",
    "NCAA School": "Cal St. Fullerton",
    "NCAA Name": "Cal State-Fullerton",
    "background-color": "#F47216",
  },
  {
    School: "Cal State Northridge",
    "City, State": "Northridge, California",
    "SR key": "cal-state-northridge",
    "NCAA key": "cal-st-northridge",
    "NCAA School": "Cal St. Northridge",
    "NCAA Name": "Cal State-Northridge",
    "background-color": "#BB2531",
  },
  {
    School: "California",
    "City, State": "Berkeley, California",
    "SR key": "california",
    "NCAA key": "california",
    "NCAA School": "California",
    "NCAA Name": "University of California",
    "background-color": "#041E42",
  },
  {
    School: "California Baptist",
    "City, State": "Riverside, California",
    "SR key": "california-baptist",
    "NCAA key": "california-baptist",
    "NCAA School": "Cal Baptist",
    "NCAA Name": "California Baptist University",
    "background-color": "#171F3B",
  },
  {
    School: "Campbell",
    "City, State": "Buies Creek, North Carolina",
    "SR key": "campbell",
    "NCAA key": "campbell",
    "NCAA School": "Campbell",
    "NCAA Name": "Campbell University",
    "background-color": "#FF4713",
  },
  {
    School: "Canisius",
    "City, State": "Buffalo, New York",
    "SR key": "canisius",
    "NCAA key": "canisius",
    "NCAA School": "Canisius",
    "NCAA Name": "Canisius College",
    "background-color": "#0C2340",
  },
  {
    School: "Central Arkansas",
    "City, State": "Conway, Arkansas",
    "SR key": "central-arkansas",
    "NCAA key": "central-ark",
    "NCAA School": "Central Ark.",
    "NCAA Name": "University of Central Arkansas",
    "background-color": "#582C83",
  },
  {
    School: "Central Connecticut State",
    "City, State": "New Britain, Connecticut",
    "SR key": "central-connecticut-state",
    "NCAA key": "central-conn-st",
    "NCAA School": "Central Conn. St.",
    "NCAA Name": "Central Connecticut State University",
    "background-color": "#003087",
  },
  {
    School: "Central Florida",
    "City, State": "Orlando, Florida",
    "SR key": "central-florida",
    "NCAA key": "ucf",
    "NCAA School": "UCF",
    "NCAA Name": "University of Central Florida",
    "background-color": "#010101",
  },
  {
    School: "Central Michigan",
    "City, State": "Mount Pleasant, Michigan",
    "SR key": "central-michigan",
    "NCAA key": "central-mich",
    "NCAA School": "Central Mich.",
    "NCAA Name": "Central Michigan University",
    "background-color": "#6F263D",
  },
  {
    School: "Charleston Southern",
    "City, State": "Charleston, South Carolina",
    "SR key": "charleston-southern",
    "NCAA key": "charleston-so",
    "NCAA School": "Charleston So.",
    "NCAA Name": "Charleston Southern University",
    "background-color": "#15233C",
  },
  {
    School: "Charlotte",
    "City, State": "Charlotte, North Carolina",
    "SR key": "charlotte",
    "NCAA key": "charlotte",
    "NCAA School": "Charlotte",
    "NCAA Name": "UNC Charlotte",
    "background-color": "#124D39",
  },
  {
    School: "Chattanooga",
    "City, State": "Chattanooga, Tennessee",
    "SR key": "chattanooga",
    "NCAA key": "chattanooga",
    "NCAA School": "Tenn-Chattanooga",
    "NCAA Name": "University of Tennessee at Chattanooga",
    "background-color": "#00416D",
  },
  {
    School: "Chicago State",
    "City, State": "Chicago, Illinois",
    "SR key": "chicago-state",
    "NCAA key": "chicago-st",
    "NCAA School": "Chicago St.",
    "NCAA Name": "Chicago State University",
    "background-color": "#006747",
  },
  {
    School: "Cincinnati",
    "City, State": "Cincinnati, Ohio",
    "SR key": "cincinnati",
    "NCAA key": "cincinnati",
    "NCAA School": "Cincinnati",
    "NCAA Name": "University of Cincinnati",
    "background-color": "#C8102E",
  },
  {
    School: "Clemson",
    "City, State": "Clemson, South Carolina",
    "SR key": "clemson",
    "NCAA key": "clemson",
    "NCAA School": "Clemson",
    "NCAA Name": "Clemson University",
    "background-color": "#FF6720",
  },
  {
    School: "Cleveland State",
    "City, State": "Cleveland, Ohio",
    "SR key": "cleveland-state",
    "NCAA key": "cleveland-st",
    "NCAA School": "Cleveland St.",
    "NCAA Name": "Cleveland State University",
    "background-color": "#115740",
  },
  {
    School: "Coastal Carolina",
    "City, State": "Conway, South Carolina",
    "SR key": "coastal-carolina",
    "NCAA key": "coastal-caro",
    "NCAA School": "Coastal Caro.",
    "NCAA Name": "Coastal Carolina University",
    "background-color": "#007377",
  },
  {
    School: "Colgate",
    "City, State": "Hamilton, New York",
    "SR key": "colgate",
    "NCAA key": "colgate",
    "NCAA School": "Colgate",
    "NCAA Name": "Colgate University",
    "background-color": "#772430",
  },
  {
    School: "College of Charleston",
    "City, State": "Charleston, South Carolina",
    "SR key": "college-of-charleston",
    "NCAA key": "col-of-charleston",
    "NCAA School": "Col. of Charleston",
    "NCAA Name": "College of Charleston",
    "background-color": "#76232F",
  },
  {
    School: "Colorado",
    "City, State": "Boulder, Colorado",
    "SR key": "colorado",
    "NCAA key": "colorado",
    "NCAA School": "Colorado",
    "NCAA Name": "University of Colorado",
    "background-color": "#010101",
  },
  {
    School: "Colorado State",
    "City, State": "Fort Collins, Colorado",
    "SR key": "colorado-state",
    "NCAA key": "colorado-st",
    "NCAA School": "Colorado St.",
    "NCAA Name": "Colorado State University",
    "background-color": "#2C5234",
  },
  {
    School: "Columbia",
    "City, State": "New York, New York",
    "SR key": "columbia",
    "NCAA key": "columbia",
    "NCAA School": "Columbia",
    "NCAA Name": "Columbia University-Barnard College",
    "background-color": "#97CAEB",
  },
  {
    School: "Connecticut",
    "City, State": "Storrs, Connecticut",
    "SR key": "connecticut",
    "NCAA key": "uconn",
    "NCAA School": "Connecticut",
    "NCAA Name": "University of Connecticut",
    "background-color": "#0C2340",
  },
  {
    School: "Coppin State",
    "City, State": "Baltimore, Maryland",
    "SR key": "coppin-state",
    "NCAA key": "coppin-st",
    "NCAA School": "Coppin St.",
    "NCAA Name": "Coppin State University",
    "background-color": "#0c3354",
  },
  {
    School: "Cornell",
    "City, State": "Ithaca, New York",
    "SR key": "cornell",
    "NCAA key": "cornell",
    "NCAA School": "Cornell",
    "NCAA Name": "Cornell University",
    "background-color": "#B32025",
  },
  {
    School: "Creighton",
    "City, State": "Omaha, Nebraska",
    "SR key": "creighton",
    "NCAA key": "creighton",
    "NCAA School": "Creighton",
    "NCAA Name": "Creighton University",
    "background-color": "#0032A0",
  },
  {
    School: "Dartmouth",
    "City, State": "Hanover, New Hampshire",
    "SR key": "dartmouth",
    "NCAA key": "dartmouth",
    "NCAA School": "Dartmouth",
    "NCAA Name": "Dartmouth College",
    "background-color": "#046A38",
  },
  {
    School: "Davidson",
    "City, State": "Davidson, North Carolina",
    "SR key": "davidson",
    "NCAA key": "davidson",
    "NCAA School": "Davidson",
    "NCAA Name": "Davidson College",
    "background-color": "#C8102E",
  },
  {
    School: "Dayton",
    "City, State": "Dayton, Ohio",
    "SR key": "dayton",
    "NCAA key": "dayton",
    "NCAA School": "Dayton",
    "NCAA Name": "University of Dayton",
    "background-color": "#D50032",
  },
  {
    School: "Delaware",
    "City, State": "Newark, Delaware",
    "SR key": "delaware",
    "NCAA key": "delaware",
    "NCAA School": "Delaware",
    "NCAA Name": "University of Delaware",
    "background-color": "#006095",
  },
  {
    School: "Delaware State",
    "City, State": "Dover, Delaware",
    "SR key": "delaware-state",
    "NCAA key": "delaware-st",
    "NCAA School": "Delaware St.",
    "NCAA Name": "Delaware State University",
    "background-color": "#DA291C",
  },
  {
    School: "Denver",
    "City, State": "Denver, Colorado",
    "SR key": "denver",
    "NCAA key": "denver",
    "NCAA School": "Denver",
    "NCAA Name": "University of Denver",
    "background-color": "#862633",
  },
  {
    School: "DePaul",
    "City, State": "Chicago, Illinois",
    "SR key": "depaul",
    "NCAA key": "depaul",
    "NCAA School": "DePaul",
    "NCAA Name": "DePaul University",
    "background-color": "#003DA5",
  },
  {
    School: "Detroit Mercy",
    "City, State": "Detroit, Michigan",
    "SR key": "detroit-mercy",
    "NCAA key": "detroit",
    "NCAA School": "Detroit",
    "NCAA Name": "University of Detroit Mercy",
    "background-color": "#A6192E",
  },
  {
    School: "Drake",
    "City, State": "Des Moines, Iowa",
    "SR key": "drake",
    "NCAA key": "drake",
    "NCAA School": "Drake",
    "NCAA Name": "Drake University",
    "background-color": "#002F6C",
  },
  {
    School: "Drexel",
    "City, State": "Philadelphia, Pennsylvania",
    "SR key": "drexel",
    "NCAA key": "drexel",
    "NCAA School": "Drexel",
    "NCAA Name": "Drexel University",
    "background-color": "#1D2D4F",
  },
  {
    School: "Duke",
    "City, State": "Durham, North Carolina",
    "SR key": "duke",
    "NCAA key": "duke",
    "NCAA School": "Duke",
    "NCAA Name": "Duke University",
    "background-color": "#002D72",
  },
  {
    School: "Duquesne",
    "City, State": "Pittsburgh, Pennsylvania",
    "SR key": "duquesne",
    "NCAA key": "duquesne",
    "NCAA School": "Duquesne",
    "NCAA Name": "Duquesne University",
    "background-color": "#BA0C2F",
  },
  {
    School: "East Carolina",
    "City, State": "Greenville, North Carolina",
    "SR key": "east-carolina",
    "NCAA key": "east-carolina",
    "NCAA School": "East Carolina",
    "NCAA Name": "East Carolina University",
    "background-color": "#582C83",
  },
  {
    School: "East Tennessee State",
    "City, State": "Johnson City, Tennessee",
    "SR key": "east-tennessee-state",
    "NCAA key": "east-tenn-st",
    "NCAA School": "East Tenn. St.",
    "NCAA Name": "East Tennessee State University",
    "background-color": "#041E42",
  },
  {
    School: "Eastern Illinois",
    "City, State": "Charleston, Illinois",
    "SR key": "eastern-illinois",
    "NCAA key": "eastern-ill",
    "NCAA School": "Eastern Ill.",
    "NCAA Name": "Eastern Illinois University",
    "background-color": "#003594",
  },
  {
    School: "Eastern Kentucky",
    "City, State": "Richmond, Kentucky",
    "SR key": "eastern-kentucky",
    "NCAA key": "eastern-ky",
    "NCAA School": "Eastern Ky.",
    "NCAA Name": "Eastern Kentucky University",
    "background-color": "#6F263D",
  },
  {
    School: "Eastern Michigan",
    "City, State": "Ypsilanti, Michigan",
    "SR key": "eastern-michigan",
    "NCAA key": "eastern-mich",
    "NCAA School": "Eastern Mich.",
    "NCAA Name": "Eastern Michigan University",
    "background-color": "#046A38",
  },
  {
    School: "Eastern Washington",
    "City, State": "Cheney, Washington",
    "SR key": "eastern-washington",
    "NCAA key": "eastern-wash",
    "NCAA School": "Eastern Wash.",
    "NCAA Name": "Eastern Washington University",
    "background-color": "#A6192E",
  },
  {
    School: "Elon",
    "City, State": "Elon, North Carolina",
    "SR key": "elon",
    "NCAA key": "elon",
    "NCAA School": "Elon",
    "NCAA Name": "Elon University",
    "background-color": "#76232F",
  },
  {
    School: "Evansville",
    "City, State": "Evansville, Indiana",
    "SR key": "evansville",
    "NCAA key": "evansville",
    "NCAA School": "Evansville",
    "NCAA Name": "University of Evansville",
    "background-color": "#470A68",
  },
  {
    School: "Fairfield",
    "City, State": "Fairfield, Connecticut",
    "SR key": "fairfield",
    "NCAA key": "fairfield",
    "NCAA School": "Fairfield",
    "NCAA Name": "Fairfield University",
    "background-color": "#C8102E",
  },
  {
    School: "Fairleigh Dickinson",
    "City, State": "Teaneck, New Jersey",
    "SR key": "fairleigh-dickinson",
    "NCAA key": "fairleigh-dickinson",
    "NCAA School": "Fairleigh Dickinson",
    "NCAA Name": "Fairleigh Dickinson University",
    "background-color": "#72293c",
  },
  {
    School: "Florida",
    "City, State": "Gainesville, Florida",
    "SR key": "florida",
    "NCAA key": "florida",
    "NCAA School": "Florida",
    "NCAA Name": "University of Florida",
    "background-color": "#003087",
  },
  {
    School: "Florida A&M",
    "City, State": "Tallahassee, Florida",
    "SR key": "florida-am",
    "NCAA key": "florida-am",
    "NCAA School": "Florida A&M",
    "NCAA Name": "Florida A&M University",
    "background-color": "#FF8200",
  },
  {
    School: "Florida Atlantic",
    "City, State": "Boca Raton, Florida",
    "SR key": "florida-atlantic",
    "NCAA key": "fla-atlantic",
    "NCAA School": "Florida Atlantic",
    "NCAA Name": "Florida Atlantic University",
    "background-color": "#002855",
  },
  {
    School: "Florida Gulf Coast",
    "City, State": "Fort Myers, Florida",
    "SR key": "florida-gulf-coast",
    "NCAA key": "fgcu",
    "NCAA School": "FGCU",
    "NCAA Name": "Florida Gulf Coast University",
    "background-color": "#002D72",
  },
  {
    School: "Florida International",
    "City, State": "Miami, Florida",
    "SR key": "florida-international",
    "NCAA key": "fiu",
    "NCAA School": "FIU",
    "NCAA Name": "Florida International University",
    "background-color": "#041E42",
  },
  {
    School: "Florida State",
    "City, State": "Tallahassee, Florida",
    "SR key": "florida-state",
    "NCAA key": "florida-st",
    "NCAA School": "Florida St.",
    "NCAA Name": "Florida State University",
    "background-color": "#76253A",
  },
  {
    School: "Fordham",
    "City, State": "Bronx, New York",
    "SR key": "fordham",
    "NCAA key": "fordham",
    "NCAA School": "Fordham",
    "NCAA Name": "Fordham University",
    "background-color": "#6F263D",
  },
  {
    School: "Fresno State",
    "City, State": "Fresno, California",
    "SR key": "fresno-state",
    "NCAA key": "fresno-st",
    "NCAA School": "Fresno St.",
    "NCAA Name": "Fresno State",
    "background-color": "#D50032",
  },
  {
    School: "Furman",
    "City, State": "Greenville, South Carolina",
    "SR key": "furman",
    "NCAA key": "furman",
    "NCAA School": "Furman",
    "NCAA Name": "Furman University",
    "background-color": "#582C83",
  },
  {
    School: "Gardner-Webb",
    "City, State": "Boiling Springs, North Carolina",
    "SR key": "gardner-webb",
    "NCAA key": "gardner-webb",
    "NCAA School": "Gardner-Webb",
    "NCAA Name": "Gardner-Webb University",
    "background-color": "#A82931",
  },
  {
    School: "George Mason",
    "City, State": "Fairfax, Virginia",
    "SR key": "george-mason",
    "NCAA key": "george-mason",
    "NCAA School": "George Mason",
    "NCAA Name": "George Mason University",
    "background-color": "#046A38",
  },
  {
    School: "George Washington",
    "City, State": "Washington, D.C.",
    "SR key": "george-washington",
    "NCAA key": "george-washington",
    "NCAA School": "George Washington",
    "NCAA Name": "George Washington University",
    "background-color": "#041E42",
  },
  {
    School: "Georgetown",
    "City, State": "Washington, D.C.",
    "SR key": "georgetown",
    "NCAA key": "georgetown",
    "NCAA School": "Georgetown",
    "NCAA Name": "Georgetown University",
    "background-color": "#141F35",
  },
  {
    School: "Georgia",
    "City, State": "Athens, Georgia",
    "SR key": "georgia",
    "NCAA key": "georgia",
    "NCAA School": "Georgia",
    "NCAA Name": "University of Georgia",
    "background-color": "#DA291C",
  },
  {
    School: "Georgia Southern",
    "City, State": "Statesboro, Georgia",
    "SR key": "georgia-southern",
    "NCAA key": "ga-southern",
    "NCAA School": "Georgia Southern",
    "NCAA Name": "Georgia Southern University",
    "background-color": "#041E42",
  },
  {
    School: "Georgia State",
    "City, State": "Atlanta, Georgia",
    "SR key": "georgia-state",
    "NCAA key": "georgia-st",
    "NCAA School": "Georgia St.",
    "NCAA Name": "Georgia State University",
    "background-color": "#264391",
  },
  {
    School: "Georgia Tech",
    "City, State": "Atlanta, Georgia",
    "SR key": "georgia-tech",
    "NCAA key": "georgia-tech",
    "NCAA School": "Georgia Tech",
    "NCAA Name": "Georgia Tech",
    "background-color": "#B3A369",
  },
  {
    School: "Gonzaga",
    "City, State": "Spokane, Washington",
    "SR key": "gonzaga",
    "NCAA key": "gonzaga",
    "NCAA School": "Gonzaga",
    "NCAA Name": "Gonzaga University",
    "background-color": "#041E42",
  },
  {
    School: "Grambling",
    "City, State": "Grambling, Louisiana",
    "SR key": "grambling",
    "NCAA key": "grambling",
    "NCAA School": "Grambling",
    "NCAA Name": "Grambling State University",
    "background-color": "#010101",
  },
  {
    School: "Grand Canyon",
    "City, State": "Phoenix, Arizona",
    "SR key": "grand-canyon",
    "NCAA key": "grand-canyon",
    "NCAA School": "Grand Canyon",
    "NCAA Name": "Grand Canyon University",
    "background-color": "#5F259F",
  },
  {
    School: "Green Bay",
    "City, State": "Green Bay, Wisconsin",
    "SR key": "green-bay",
    "NCAA key": "green-bay",
    "NCAA School": "Green Bay",
    "NCAA Name": "University of Wisconsin, Green Bay",
    "background-color": "#0F5640",
  },
  {
    School: "Hampton",
    "City, State": "Hampton, Virginia",
    "SR key": "hampton",
    "NCAA key": "hampton",
    "NCAA School": "Hampton",
    "NCAA Name": "Hampton University",
    "background-color": "#0033A0",
  },
  {
    School: "Harvard",
    "City, State": "Boston, Massachusetts",
    "SR key": "harvard",
    "NCAA key": "harvard",
    "NCAA School": "Harvard",
    "NCAA Name": "Harvard University",
    "background-color": "#912235",
  },
  {
    School: "Hawaii",
    "City, State": "Honolulu, Hawaii",
    "SR key": "hawaii",
    "NCAA key": "hawaii",
    "NCAA School": "Hawaii",
    "NCAA Name": "University of Hawaii, Manoa",
    "background-color": "#154734",
  },
  {
    School: "High Point",
    "City, State": "High Point, North Carolina",
    "SR key": "high-point",
    "NCAA key": "high-point",
    "NCAA School": "High Point",
    "NCAA Name": "High Point University",
    "background-color": "#330072",
  },
  {
    School: "Hofstra",
    "City, State": "Hempstead, New York",
    "SR key": "hofstra",
    "NCAA key": "hofstra",
    "NCAA School": "Hofstra",
    "NCAA Name": "Hofstra University",
    "background-color": "#003594",
  },
  {
    School: "Holy Cross",
    "City, State": "Worcester, Massachusetts",
    "SR key": "holy-cross",
    "NCAA key": "holy-cross",
    "NCAA School": "Holy Cross",
    "NCAA Name": "College of the Holy Cross",
    "background-color": "#582C83",
  },
  {
    School: "Houston",
    "City, State": "Houston, Texas",
    "SR key": "houston",
    "NCAA key": "houston",
    "NCAA School": "Houston",
    "NCAA Name": "University of Houston",
    "background-color": "#E51636",
  },
  {
    School: "Houston Christian",
    "City, State": "Houston, Texas",
    "SR key": "houston-baptist",
    "NCAA key": "houston-baptist",
    "NCAA School": "Houston Christian",
    "NCAA Name": "Houston Christian University",
    "background-color": "#002F87",
  },
  {
    School: "Howard",
    "City, State": "Washington, D.C.",
    "SR key": "howard",
    "NCAA key": "howard",
    "NCAA School": "Howard",
    "NCAA Name": "Howard University",
    "background-color": "#00263E",
  },
  {
    School: "Idaho",
    "City, State": "Moscow, Idaho",
    "SR key": "idaho",
    "NCAA key": "idaho",
    "NCAA School": "Idaho",
    "NCAA Name": "University of Idaho",
    "background-color": "#010101",
  },
  {
    School: "Idaho State",
    "City, State": "Pocatello, Idaho",
    "SR key": "idaho-state",
    "NCAA key": "idaho-st",
    "NCAA School": "Idaho St.",
    "NCAA Name": "Idaho State University",
    "background-color": "#F47920",
  },
  {
    School: "Illinois",
    "City, State": "Champaign, Illinois",
    "SR key": "illinois",
    "NCAA key": "illinois",
    "NCAA School": "Illinois",
    "NCAA Name": "University of Illinois",
    "background-color": "#F15A22",
  },
  {
    School: "Illinois State",
    "City, State": "Normal, Illinois",
    "SR key": "illinois-state",
    "NCAA key": "illinois-st",
    "NCAA School": "Illinois St.",
    "NCAA Name": "Illinois State University",
    "background-color": "#C8102E",
  },
  {
    School: "Illinois-Chicago",
    "City, State": "Chicago, Illinois",
    "SR key": "illinois-chicago",
    "NCAA key": "ill-chicago",
    "NCAA School": "Ill.-Chicago",
    "NCAA Name": "University of Illinois-Chicago",
    "background-color": "#DB0032",
  },
  {
    School: "Incarnate Word",
    "City, State": "San Antonio, Texas",
    "SR key": "incarnate-word",
    "NCAA key": "incarnate-word",
    "NCAA School": "UIW",
    "NCAA Name": "University of the Incarnate Word",
    "background-color": undefined,
  },
  {
    School: "Indiana",
    "City, State": "Bloomington, Indiana",
    "SR key": "indiana",
    "NCAA key": "indiana",
    "NCAA School": "Indiana",
    "NCAA Name": "Indiana University, Bloomington",
    "background-color": "#970310",
  },
  {
    School: "Indiana State",
    "City, State": "Terre Haute, Indiana",
    "SR key": "indiana-state",
    "NCAA key": "indiana-st",
    "NCAA School": "Indiana St.",
    "NCAA Name": "Indiana State University",
    "background-color": "#1E437B",
  },
  {
    School: "Iona",
    "City, State": "New Rochelle, New York",
    "SR key": "iona",
    "NCAA key": "iona",
    "NCAA School": "Iona",
    "NCAA Name": "Iona College",
    "background-color": "#6F2C3F",
  },
  {
    School: "Iowa",
    "City, State": "Iowa City, Iowa",
    "SR key": "iowa",
    "NCAA key": "iowa",
    "NCAA School": "Iowa",
    "NCAA Name": "University of Iowa",
    "background-color": "#010101",
  },
  {
    School: "Iowa State",
    "City, State": "Ames, Iowa",
    "SR key": "iowa-state",
    "NCAA key": "iowa-st",
    "NCAA School": "Iowa St.",
    "NCAA Name": "Iowa State University",
    "background-color": "#A6192E",
  },
  {
    School: "IUPUI",
    "City, State": "Indianapolis, Indiana",
    "SR key": "iupui",
    "NCAA key": "iupui",
    "NCAA School": "IUPUI",
    "NCAA Name": "IUPUI",
    "background-color": "#9D2235",
  },
  {
    School: "Jackson State",
    "City, State": "Jackson, Mississippi",
    "SR key": "jackson-state",
    "NCAA key": "jackson-st",
    "NCAA School": "Jackson St.",
    "NCAA Name": "Jackson State University",
    "background-color": "#041E42",
  },
  {
    School: "Jacksonville",
    "City, State": "Jacksonville, Florida",
    "SR key": "jacksonville",
    "NCAA key": "jacksonville",
    "NCAA School": "Jacksonville",
    "NCAA Name": "Jacksonville University",
    "background-color": "#004E42",
  },
  {
    School: "Jacksonville State",
    "City, State": "Jacksonville, Alabama",
    "SR key": "jacksonville-state",
    "NCAA key": "jacksonville-st",
    "NCAA School": "Jacksonville St.",
    "NCAA Name": "Jacksonville State University",
    "background-color": "#C8102E",
  },
  {
    School: "James Madison",
    "City, State": "Harrisonburg, Virginia",
    "SR key": "james-madison",
    "NCAA key": "james-madison",
    "NCAA School": "James Madison",
    "NCAA Name": "James Madison University",
    "background-color": "#330072",
  },
  {
    School: "Kansas",
    "City, State": "Lawrence, Kansas",
    "SR key": "kansas",
    "NCAA key": "kansas",
    "NCAA School": "Kansas",
    "NCAA Name": "University of Kansas",
    "background-color": "#1967B8",
  },
  {
    School: "Kansas City",
    "City, State": "Kansas City, Missouri",
    "SR key": "missouri-kansas-city",
    "NCAA key": "umkc",
    "NCAA School": "Kansas City",
    "NCAA Name": "University of Missouri-Kansas City",
    "background-color": "#004B87",
  },
  {
    School: "Kansas State",
    "City, State": "Manhattan, Kansas",
    "SR key": "kansas-state",
    "NCAA key": "kansas-st",
    "NCAA School": "Kansas St.",
    "NCAA Name": "Kansas State University",
    "background-color": "#582C83",
  },
  {
    School: "Kennesaw State",
    "City, State": "Kennesaw, Georgia",
    "SR key": "kennesaw-state",
    "NCAA key": "kennesaw-st",
    "NCAA School": "Kennesaw St.",
    "NCAA Name": "Kennesaw State University",
    "background-color": "#010101",
  },
  {
    School: "Kent State",
    "City, State": "Kent, Ohio",
    "SR key": "kent-state",
    "NCAA key": "kent-st",
    "NCAA School": "Kent St.",
    "NCAA Name": "Kent State University",
    "background-color": "#003976",
  },
  {
    School: "Kentucky",
    "City, State": "Lexington, Kentucky",
    "SR key": "kentucky",
    "NCAA key": "kentucky",
    "NCAA School": "Kentucky",
    "NCAA Name": "University of Kentucky",
    "background-color": "#3258AF",
  },
  {
    School: "La Salle",
    "City, State": "Philadelphia, Pennsylvania",
    "SR key": "la-salle",
    "NCAA key": "la-salle",
    "NCAA School": "La Salle",
    "NCAA Name": "La Salle University",
    "background-color": "#003057",
  },
  {
    School: "Lafayette",
    "City, State": "Easton, Pennsylvania",
    "SR key": "lafayette",
    "NCAA key": "lafayette",
    "NCAA School": "Lafayette",
    "NCAA Name": "Lafayette College",
    "background-color": "#862633",
  },
  {
    School: "Lamar",
    "City, State": "Beaumont, Texas",
    "SR key": "lamar",
    "NCAA key": "lamar",
    "NCAA School": "Lamar",
    "NCAA Name": "Lamar University",
    "background-color": "#D50032",
  },
  {
    School: "Le Moyne",
    "City, State": "Syracuse, New York",
    "SR key": "le-moyne",
    "NCAA key": "le-moyne",
    "NCAA School": "Le Moyne",
    "NCAA Name": "Le Moyne College",
    "background-color": "#154734",
  },
  {
    School: "Lehigh",
    "City, State": "Bethlehem, Pennsylvania",
    "SR key": "lehigh",
    "NCAA key": "lehigh",
    "NCAA School": "Lehigh",
    "NCAA Name": "Lehigh University",
    "background-color": "#653819",
  },
  {
    School: "Liberty",
    "City, State": "Lynchburg, Virginia",
    "SR key": "liberty",
    "NCAA key": "liberty",
    "NCAA School": "Liberty",
    "NCAA Name": "Liberty University",
    "background-color": "#971A1F",
  },
  {
    School: "Lindenwood",
    "City, State": "St. Charles, Missouri",
    "SR key": "lindenwood",
    "NCAA key": "lindenwood-mo",
    "NCAA School": "Lindenwood",
    "NCAA Name": "Lindenwood University",
    "background-color": "#010101",
  },
  {
    School: "Lipscomb",
    "City, State": "Nashville, Tennessee",
    "SR key": "lipscomb",
    "NCAA key": "lipscomb",
    "NCAA School": "Lipscomb",
    "NCAA Name": "Lipscomb University",
    "background-color": "#2E1A47",
  },
  {
    School: "Little Rock",
    "City, State": "Little Rock, Arkansas",
    "SR key": "arkansas-little-rock",
    "NCAA key": "ualr",
    "NCAA School": "Little-Rock",
    "NCAA Name": "Little Rock",
    "background-color": "#6F263D",
  },
  {
    School: "Long Beach State",
    "City, State": "Long Beach, California",
    "SR key": "long-beach-state",
    "NCAA key": "long-beach-st",
    "NCAA School": "Long Beach St.",
    "NCAA Name": "Long Beach State University",
    "background-color": "#010101",
  },
  {
    School: "Long Island University",
    "City, State": "Brooklyn, New York",
    "SR key": "long-island-university",
    "NCAA key": "long-island",
    "NCAA School": "Long Island",
    "NCAA Name": "Long Island University",
    "background-color": "#68A8D0",
  },
  {
    School: "Longwood",
    "City, State": "Farmville, Virginia",
    "SR key": "longwood",
    "NCAA key": "longwood",
    "NCAA School": "Longwood",
    "NCAA Name": "Longwood University",
    "background-color": "#041E42",
  },
  {
    School: "Louisiana",
    "City, State": "Lafayette, Louisiana",
    "SR key": "louisiana-lafayette",
    "NCAA key": "la-lafayette",
    "NCAA School": "La.-Lafayette",
    "NCAA Name": "University of Louisiana at Lafayette",
    "background-color": "#C8102E",
  },
  {
    School: "Louisiana State",
    "City, State": "Baton Rouge, Louisiana",
    "SR key": "louisiana-state",
    "NCAA key": "lsu",
    "NCAA School": "LSU",
    "NCAA Name": "Louisiana State University",
    "background-color": "#582C83",
  },
  {
    School: "Louisiana Tech",
    "City, State": "Ruston, Louisiana",
    "SR key": "louisiana-tech",
    "NCAA key": "louisiana-tech",
    "NCAA School": "Louisiana Tech",
    "NCAA Name": "Louisiana Tech University",
    "background-color": "#003087",
  },
  {
    School: "Louisiana-Monroe",
    "City, State": "Monroe, Louisiana",
    "SR key": "louisiana-monroe",
    "NCAA key": "la-monroe",
    "NCAA School": "La.-Monroe",
    "NCAA Name": "University of Louisiana at Monroe",
    "background-color": "#8A2432",
  },
  {
    School: "Louisville",
    "City, State": "Louisville, Kentucky",
    "SR key": "louisville",
    "NCAA key": "louisville",
    "NCAA School": "Louisville",
    "NCAA Name": "University of Louisville",
    "background-color": "#EE2722",
  },
  {
    School: "Loyola (IL)",
    "City, State": "Chicago, Illinois",
    "SR key": "loyola-il",
    "NCAA key": "loyola-chicago",
    "NCAA School": "Loyola (IL)",
    "NCAA Name": "Loyola University Chicago",
    "background-color": "#861F41",
  },
  {
    School: "Loyola (MD)",
    "City, State": "Baltimore, Maryland",
    "SR key": "loyola-md",
    "NCAA key": "loyola-maryland",
    "NCAA School": "Loyola Maryland",
    "NCAA Name": "Loyola University Maryland",
    "background-color": "#115740",
  },
  {
    School: "Loyola Marymount",
    "City, State": "Los Angeles, California",
    "SR key": "loyola-marymount",
    "NCAA key": "loyola-marymount",
    "NCAA School": "Loyola Marymount",
    "NCAA Name": "Loyola Marymount University",
    "background-color": "#AB0C2F",
  },
  {
    School: "Maine",
    "City, State": "Orono, Maine",
    "SR key": "maine",
    "NCAA key": "maine",
    "NCAA School": "Maine",
    "NCAA Name": "University of Maine",
    "background-color": "#0C2340",
  },
  {
    School: "Manhattan",
    "City, State": "Riverdale, New York",
    "SR key": "manhattan",
    "NCAA key": "manhattan",
    "NCAA School": "Manhattan",
    "NCAA Name": "Manhattan College",
    "background-color": "#046A38",
  },
  {
    School: "Marist",
    "City, State": "Poughkeepsie, New York",
    "SR key": "marist",
    "NCAA key": "marist",
    "NCAA School": "Marist",
    "NCAA Name": "Marist College",
    "background-color": "#C8102E",
  },
  {
    School: "Marquette",
    "City, State": "Milwaukee, Wisconsin",
    "SR key": "marquette",
    "NCAA key": "marquette",
    "NCAA School": "Marquette",
    "NCAA Name": "Marquette University",
    "background-color": "#1D2953",
  },
  {
    School: "Marshall",
    "City, State": "Huntington, West Virginia",
    "SR key": "marshall",
    "NCAA key": "marshall",
    "NCAA School": "Marshall",
    "NCAA Name": "Marshall University",
    "background-color": "#00B140",
  },
  {
    School: "Maryland",
    "City, State": "College Park, Maryland",
    "SR key": "maryland",
    "NCAA key": "maryland",
    "NCAA School": "Maryland",
    "NCAA Name": "University of Maryland-College Park",
    "background-color": "#C8102E",
  },
  {
    School: "Maryland-Baltimore County",
    "City, State": "Baltimore, Maryland",
    "SR key": "maryland-baltimore-county",
    "NCAA key": "umbc",
    "NCAA School": "Maryland-Baltimore-County",
    "NCAA Name": "UMBC",
    "background-color": "#010101",
  },
  {
    School: "Maryland-Eastern Shore",
    "City, State": "Princess Anne, Maryland",
    "SR key": "maryland-eastern-shore",
    "NCAA key": "umes",
    "NCAA School": undefined,
    "NCAA Name": undefined,
    "background-color": undefined,
  },
  {
    School: "Massachusetts",
    "City, State": "Amherst, Massachusetts",
    "SR key": "massachusetts",
    "NCAA key": "massachusetts",
    "NCAA School": "Mass-Amherst",
    "NCAA Name": "University of Massachusetts",
    "background-color": "#732122",
  },
  {
    School: "Massachusetts-Lowell",
    "City, State": "Lowell, Massachusetts",
    "SR key": "massachusetts-lowell",
    "NCAA key": "umass-lowell",
    "NCAA School": "Mass.-Lowell",
    "NCAA Name": "UMass Lowell",
    "background-color": "#003DA5",
  },
  {
    School: "McNeese State",
    "City, State": "Lake Charles, Louisiana",
    "SR key": "mcneese-state",
    "NCAA key": "mcneese-st",
    "NCAA School": "McNeese St.",
    "NCAA Name": "McNeese State University",
    "background-color": "#003087",
  },
  {
    School: "Memphis",
    "City, State": "Memphis, Tennessee",
    "SR key": "memphis",
    "NCAA key": "memphis",
    "NCAA School": "Memphis",
    "NCAA Name": "University of Memphis",
    "background-color": "#173B70",
  },
  {
    School: "Mercer",
    "City, State": "Macon, Georgia",
    "SR key": "mercer",
    "NCAA key": "mercer",
    "NCAA School": "Mercer",
    "NCAA Name": "Mercer University",
    "background-color": "#E87722",
  },
  {
    School: "Merrimack",
    "City, State": "North Andover, Massachusetts",
    "SR key": "merrimack",
    "NCAA key": "merrimack",
    "NCAA School": "Merrimack",
    "NCAA Name": "Merrimack College",
    "background-color": "#003057",
  },
  {
    School: "Miami (FL)",
    "City, State": "Coral Gables, Florida",
    "SR key": "miami-fl",
    "NCAA key": "miami-fl",
    "NCAA School": "Miami (Fla.)",
    "NCAA Name": "University of Miami",
    "background-color": "#154734",
  },
  {
    School: "Miami (OH)",
    "City, State": "Oxford, Ohio",
    "SR key": "miami-oh",
    "NCAA key": "miami-oh",
    "NCAA School": "Miami (OH)",
    "NCAA Name": "Miami University (Ohio)",
    "background-color": "#C8102E",
  },
  {
    School: "Michigan",
    "City, State": "Ann Arbor, Michigan",
    "SR key": "michigan",
    "NCAA key": "michigan",
    "NCAA School": "Michigan",
    "NCAA Name": "University of Michigan",
    "background-color": "#041E42",
  },
  {
    School: "Michigan State",
    "City, State": "East Lansing, Michigan",
    "SR key": "michigan-state",
    "NCAA key": "michigan-st",
    "NCAA School": "Michigan St.",
    "NCAA Name": "Michigan State University",
    "background-color": "#173F35",
  },
  {
    School: "Middle Tennessee",
    "City, State": "Murfreesboro, Tennessee",
    "SR key": "middle-tennessee",
    "NCAA key": "middle-tenn",
    "NCAA School": "Middle Tenn.",
    "NCAA Name": "Middle Tennessee State University",
    "background-color": "#006FAB",
  },
  {
    School: "Milwaukee",
    "City, State": "Milwaukee, Wisconsin",
    "SR key": "milwaukee",
    "NCAA key": "milwaukee",
    "NCAA School": "Milwaukee",
    "NCAA Name": "University of Wisconsin, Milwaukee",
    "background-color": "#010101",
  },
  {
    School: "Minnesota",
    "City, State": "Minneapolis, Minnesota",
    "SR key": "minnesota",
    "NCAA key": "minnesota",
    "NCAA School": "Minnesota",
    "NCAA Name": "University of Minnesota",
    "background-color": "#861F41",
  },
  {
    School: "Mississippi",
    "City, State": "University, Mississippi",
    "SR key": "mississippi",
    "NCAA key": "ole-miss",
    "NCAA School": "Mississippi",
    "NCAA Name": "University of Mississippi",
    "background-color": "#C8102E",
  },
  {
    School: "Mississippi State",
    "City, State": "Mississippi State, Mississippi",
    "SR key": "mississippi-state",
    "NCAA key": "mississippi-st",
    "NCAA School": "Mississippi St.",
    "NCAA Name": "Mississippi State University",
    "background-color": "#5D1725",
  },
  {
    School: "Mississippi Valley State",
    "City, State": "Itta Bena, Mississippi",
    "SR key": "mississippi-valley-state",
    "NCAA key": "mississippi-val",
    "NCAA School": "Mississippi Val.",
    "NCAA Name": "Mississippi Valley State University",
    "background-color": "#046A38",
  },
  {
    School: "Missouri",
    "City, State": "Columbia, Missouri",
    "SR key": "missouri",
    "NCAA key": "missouri",
    "NCAA School": "Missouri",
    "NCAA Name": "University of Missouri",
    "background-color": "#010101",
  },
  {
    School: "Missouri State",
    "City, State": "Springfield, Missouri",
    "SR key": "missouri-state",
    "NCAA key": "missouri-st",
    "NCAA School": "Missouri St.",
    "NCAA Name": "Missouri State University",
    "background-color": "#6F2C3F",
  },
  {
    School: "Monmouth",
    "City, State": "West Long Branch, New Jersey",
    "SR key": "monmouth",
    "NCAA key": "monmouth",
    "NCAA School": "Monmouth",
    "NCAA Name": "Monmouth University",
    "background-color": "#041E42",
  },
  {
    School: "Montana",
    "City, State": "Missoula, Montana",
    "SR key": "montana",
    "NCAA key": "montana",
    "NCAA School": "Montana",
    "NCAA Name": "University of Montana",
    "background-color": "#6F2C3F",
  },
  {
    School: "Montana State",
    "City, State": "Bozeman, Montana",
    "SR key": "montana-state",
    "NCAA key": "montana-st",
    "NCAA School": "Montana St.",
    "NCAA Name": "Montana State University-Bozeman",
    "background-color": "#00205B",
  },
  {
    School: "Morehead State",
    "City, State": "Morehead, Kentucky",
    "SR key": "morehead-state",
    "NCAA key": "morehead-st",
    "NCAA School": "Morehead St.",
    "NCAA Name": "Morehead State University",
    "background-color": "#0032A0",
  },
  {
    School: "Morgan State",
    "City, State": "Baltimore, Maryland",
    "SR key": "morgan-state",
    "NCAA key": "morgan-st",
    "NCAA School": "Morgan St.",
    "NCAA Name": "Morgan State University",
    "background-color": "#FC4C02",
  },
  {
    School: "Mount St. Mary's",
    "City, State": "Emmitsburg, Maryland",
    "SR key": "mount-st-marys",
    "NCAA key": "mt-st-marys",
    "NCAA School": "Mt. St. Mary's",
    "NCAA Name": "Mount St. Mary's University",
    "background-color": "#002F6C",
  },
  {
    School: "Murray State",
    "City, State": "Murray, Kentucky",
    "SR key": "murray-state",
    "NCAA key": "murray-st",
    "NCAA School": "Murray St.",
    "NCAA Name": "Murray State University",
    "background-color": "#0C2340",
  },
  {
    School: "Navy",
    "City, State": "Annapolis, Maryland",
    "SR key": "navy",
    "NCAA key": "navy",
    "NCAA School": "Navy",
    "NCAA Name": "U.S. Naval Academy",
    "background-color": "#00205B",
  },
  {
    School: "NC State",
    "City, State": "Raleigh, North Carolina",
    "SR key": "north-carolina-state",
    "NCAA key": "north-carolina-st",
    "NCAA School": "North Carolina St.",
    "NCAA Name": "North Carolina State University",
    "background-color": "#C8102E",
  },
  {
    School: "Nebraska",
    "City, State": "Lincoln, Nebraska",
    "SR key": "nebraska",
    "NCAA key": "nebraska",
    "NCAA School": "Nebraska",
    "NCAA Name": "University of Nebraska-Lincoln",
    "background-color": "#C8102E",
  },
  {
    School: "Nevada",
    "City, State": "Reno, Nevada",
    "SR key": "nevada",
    "NCAA key": "nevada",
    "NCAA School": "Nevada",
    "NCAA Name": "University of Nevada",
    "background-color": "#041E42",
  },
  {
    School: "Nevada-Las Vegas",
    "City, State": "Las Vegas, Nevada",
    "SR key": "nevada-las-vegas",
    "NCAA key": "unlv",
    "NCAA School": "UNLV",
    "NCAA Name": "UNLV",
    "background-color": "#C8102E",
  },
  {
    School: "New Hampshire",
    "City, State": "Durham, New Hampshire",
    "SR key": "new-hampshire",
    "NCAA key": "new-hampshire",
    "NCAA School": "New Hampshire",
    "NCAA Name": "University of New Hampshire",
    "background-color": "#041E42",
  },
  {
    School: "New Mexico",
    "City, State": "Albuquerque, New Mexico",
    "SR key": "new-mexico",
    "NCAA key": "new-mexico",
    "NCAA School": "New Mexico",
    "NCAA Name": "University of New Mexico",
    "background-color": "#BA0C2F",
  },
  {
    School: "New Mexico State",
    "City, State": "Las Cruces, New Mexico",
    "SR key": "new-mexico-state",
    "NCAA key": "new-mexico-st",
    "NCAA School": "New Mexico St.",
    "NCAA Name": "New Mexico State University",
    "background-color": "#891619",
  },
  {
    School: "New Orleans",
    "City, State": "New Orleans, Louisiana",
    "SR key": "new-orleans",
    "NCAA key": "new-orleans",
    "NCAA School": "New Orleans",
    "NCAA Name": "University of New Orleans",
    "background-color": "#0057B8",
  },
  {
    School: "Niagara",
    "City, State": "Niagara University, New York",
    "SR key": "niagara",
    "NCAA key": "niagara",
    "NCAA School": "Niagara",
    "NCAA Name": "Niagara University",
    "background-color": "#582C83",
  },
  {
    School: "Nicholls State",
    "City, State": "Thibodaux, Louisiana",
    "SR key": "nicholls-state",
    "NCAA key": "nicholls-st",
    "NCAA School": "Nicholls St.",
    "NCAA Name": "Nicholls State University",
    "background-color": "#A6192E",
  },
  {
    School: "NJIT",
    "City, State": "Newark, New Jersey",
    "SR key": "njit",
    "NCAA key": "njit",
    "NCAA School": "New-Jersey-Tech",
    "NCAA Name": "New Jersey Institute of Technology",
    "background-color": "#D22630",
  },
  {
    School: "Norfolk State",
    "City, State": "Norfolk, Virginia",
    "SR key": "norfolk-state",
    "NCAA key": "norfolk-st",
    "NCAA School": "Norfolk St.",
    "NCAA Name": "Norfolk State University",
    "background-color": "#007A53",
  },
  {
    School: "North Alabama",
    "City, State": "Florence, Alabama",
    "SR key": "north-alabama",
    "NCAA key": "north-ala",
    "NCAA School": "North Ala.",
    "NCAA Name": "University of North Alabama",
    "background-color": "#582C83",
  },
  {
    School: "North Carolina",
    "City, State": "Chapel Hill, North Carolina",
    "SR key": "north-carolina",
    "NCAA key": "north-carolina",
    "NCAA School": "North Carolina",
    "NCAA Name": "University of North Carolina",
    "background-color": "#7BAFD4",
  },
  {
    School: "North Carolina A&T",
    "City, State": "Greensboro, North Carolina",
    "SR key": "north-carolina-at",
    "NCAA key": "nc-at",
    "NCAA School": "North Carolina A&T",
    "NCAA Name": "North Carolina A&T State University",
    "background-color": "#002D72",
  },
  {
    School: "North Carolina Central",
    "City, State": "Durham, North Carolina",
    "SR key": "north-carolina-central",
    "NCAA key": "nc-central",
    "NCAA School": "North Carolina Central",
    "NCAA Name": "North Carolina Central University",
    "background-color": "#862633",
  },
  {
    School: "North Dakota",
    "City, State": "Grand Forks, North Dakota",
    "SR key": "north-dakota",
    "NCAA key": "north-dakota",
    "NCAA School": "North Dakota",
    "NCAA Name": "University of North Dakota",
    "background-color": "#009A44",
  },
  {
    School: "North Dakota State",
    "City, State": "Fargo, North Dakota",
    "SR key": "north-dakota-state",
    "NCAA key": "north-dakota-st",
    "NCAA School": "North Dakota St.",
    "NCAA Name": "North Dakota State University",
    "background-color": "#115740",
  },
  {
    School: "North Florida",
    "City, State": "Jacksonville, Florida",
    "SR key": "north-florida",
    "NCAA key": "north-florida",
    "NCAA School": "North Florida",
    "NCAA Name": "University of North Florida",
    "background-color": "#0C2340",
  },
  {
    School: "North Texas",
    "City, State": "Denton, Texas",
    "SR key": "north-texas",
    "NCAA key": "north-texas",
    "NCAA School": "North Texas",
    "NCAA Name": "University of North Texas",
    "background-color": "#007A33",
  },
  {
    School: "Northeastern",
    "City, State": "Boston, Massachusetts",
    "SR key": "northeastern",
    "NCAA key": "northeastern",
    "NCAA School": "Northeastern",
    "NCAA Name": "Northeastern University",
    "background-color": "#C8102E",
  },
  {
    School: "Northern Arizona",
    "City, State": "Flagstaff, Arizona",
    "SR key": "northern-arizona",
    "NCAA key": "northern-ariz",
    "NCAA School": "Northern Ariz.",
    "NCAA Name": "Northern Arizona University",
    "background-color": "#00205B",
  },
  {
    School: "Northern Colorado",
    "City, State": "Greeley, Colorado",
    "SR key": "northern-colorado",
    "NCAA key": "northern-colo",
    "NCAA School": "Northern Colo.",
    "NCAA Name": "University of Northern Colorado",
    "background-color": "#002855",
  },
  {
    School: "Northern Illinois",
    "City, State": "De Kalb, Illinois",
    "SR key": "northern-illinois",
    "NCAA key": "northern-ill",
    "NCAA School": "Northern Ill.",
    "NCAA Name": "Northern Illinois University",
    "background-color": "#BA0C2F",
  },
  {
    School: "Northern Iowa",
    "City, State": "Cedar Falls, Iowa",
    "SR key": "northern-iowa",
    "NCAA key": "uni",
    "NCAA School": "Northern Iowa",
    "NCAA Name": "University of Northern Iowa",
    "background-color": "#470A68",
  },
  {
    School: "Northern Kentucky",
    "City, State": "Highland Heights, Kentucky",
    "SR key": "northern-kentucky",
    "NCAA key": "northern-ky",
    "NCAA School": "Northern Ky.",
    "NCAA Name": "Northern Kentucky University",
    "background-color": "#010101",
  },
  {
    School: "Northwestern",
    "City, State": "Evanston, Illinois",
    "SR key": "northwestern",
    "NCAA key": "northwestern",
    "NCAA School": "Northwestern",
    "NCAA Name": "Northwestern University",
    "background-color": "#4E2A84",
  },
  {
    School: "Northwestern State",
    "City, State": "Natchitoches, Louisiana",
    "SR key": "northwestern-state",
    "NCAA key": "northwestern-st",
    "NCAA School": "Northwestern St.",
    "NCAA Name": "Northwestern State University",
    "background-color": "#54209e",
  },
  {
    School: "Notre Dame",
    "City, State": "Notre Dame, Indiana",
    "SR key": "notre-dame",
    "NCAA key": "notre-dame",
    "NCAA School": "Notre Dame",
    "NCAA Name": "University of Notre Dame",
    "background-color": "#0C2340",
  },
  {
    School: "Oakland",
    "City, State": "Rochester, Michigan",
    "SR key": "oakland",
    "NCAA key": "oakland",
    "NCAA School": "Oakland",
    "NCAA Name": "Oakland University",
    "background-color": "#010101",
  },
  {
    School: "Ohio",
    "City, State": "Athens, Ohio",
    "SR key": "ohio",
    "NCAA key": "ohio",
    "NCAA School": "Ohio",
    "NCAA Name": "Ohio University",
    "background-color": "#154734",
  },
  {
    School: "Ohio State",
    "City, State": "Columbus, Ohio",
    "SR key": "ohio-state",
    "NCAA key": "ohio-st",
    "NCAA School": "Ohio St.",
    "NCAA Name": "The Ohio State University",
    "background-color": "#CE0F3E",
  },
  {
    School: "Oklahoma",
    "City, State": "Norman, Oklahoma",
    "SR key": "oklahoma",
    "NCAA key": "oklahoma",
    "NCAA School": "Oklahoma",
    "NCAA Name": "University of Oklahoma",
    "background-color": "#9D2235",
  },
  {
    School: "Oklahoma State",
    "City, State": "Stillwater, Oklahoma",
    "SR key": "oklahoma-state",
    "NCAA key": "oklahoma-st",
    "NCAA School": "Oklahoma St.",
    "NCAA Name": "Oklahoma State University",
    "background-color": "#DF4F2A",
  },
  {
    School: "Old Dominion",
    "City, State": "Norfolk, Virginia",
    "SR key": "old-dominion",
    "NCAA key": "old-dominion",
    "NCAA School": "Old Dominion",
    "NCAA Name": "Old Dominion University",
    "background-color": "#0B4071",
  },
  {
    School: "Omaha",
    "City, State": "Omaha, Nebraska",
    "SR key": "nebraska-omaha",
    "NCAA key": "neb-omaha",
    "NCAA School": "Omaha",
    "NCAA Name": "University of Nebraska-Omaha",
    "background-color": "#010101",
  },
  {
    School: "Oral Roberts",
    "City, State": "Tulsa, Oklahoma",
    "SR key": "oral-roberts",
    "NCAA key": "oral-roberts",
    "NCAA School": "Oral Roberts",
    "NCAA Name": "Oral Roberts University",
    "background-color": "#011E41",
  },
  {
    School: "Oregon",
    "City, State": "Eugene, Oregon",
    "SR key": "oregon",
    "NCAA key": "oregon",
    "NCAA School": "Oregon",
    "NCAA Name": "University of Oregon",
    "background-color": "#173F35",
  },
  {
    School: "Oregon State",
    "City, State": "Corvallis, Oregon",
    "SR key": "oregon-state",
    "NCAA key": "oregon-st",
    "NCAA School": "Oregon State",
    "NCAA Name": "Oregon State University",
    "background-color": "#DC4405",
  },
  {
    School: "Pacific",
    "City, State": "Stockton, California",
    "SR key": "pacific",
    "NCAA key": "pacific-or",
    "NCAA School": "Pacific (OR)",
    "NCAA Name": "Pacific University",
    "background-color": "#b4183a",
  },
  {
    School: "Penn State",
    "City, State": "University Park, Pennsylvania",
    "SR key": "penn-state",
    "NCAA key": "penn-st",
    "NCAA School": "Penn State",
    "NCAA Name": "Penn State University",
    "background-color": "#041E42",
  },
  {
    School: "Pennsylvania",
    "City, State": "Philadelphia, Pennsylvania",
    "SR key": "pennsylvania",
    "NCAA key": "penn",
    "NCAA School": "Penn",
    "NCAA Name": "University of Pennsylvania",
    "background-color": "#002D72",
  },
  {
    School: "Pepperdine",
    "City, State": "Malibu, California",
    "SR key": "pepperdine",
    "NCAA key": "pepperdine",
    "NCAA School": "Pepperdine",
    "NCAA Name": "Pepperdine University",
    "background-color": "#00205B",
  },
  {
    School: "Pittsburgh",
    "City, State": "Pittsburgh, Pennsylvania",
    "SR key": "pittsburgh",
    "NCAA key": "pittsburgh",
    "NCAA School": "Pittsburgh",
    "NCAA Name": "University of Pittsburgh",
    "background-color": "#003594",
  },
  {
    School: "Portland",
    "City, State": "Portland, Oregon",
    "SR key": "portland",
    "NCAA key": "portland",
    "NCAA School": "Portland",
    "NCAA Name": "University of Portland",
    "background-color": "#31006F",
  },
  {
    School: "Portland State",
    "City, State": "Portland, Oregon",
    "SR key": "portland-state",
    "NCAA key": "portland-st",
    "NCAA School": "Portland St.",
    "NCAA Name": "Portland State University",
    "background-color": "#154734",
  },
  {
    School: "Prairie View",
    "City, State": "Prairie View, Texas",
    "SR key": "prairie-view",
    "NCAA key": "prairie-view",
    "NCAA School": "Prairie View",
    "NCAA Name": "Prairie View A&M University",
    "background-color": "#582C83",
  },
  {
    School: "Presbyterian",
    "City, State": "Clinton, South Carolina",
    "SR key": "presbyterian",
    "NCAA key": "presbyterian",
    "NCAA School": "Presbyterian",
    "NCAA Name": "Presbyterian College",
    "background-color": "#005394",
  },
  {
    School: "Princeton",
    "City, State": "Princeton, New Jersey",
    "SR key": "princeton",
    "NCAA key": "princeton",
    "NCAA School": "Princeton",
    "NCAA Name": "Princeton University",
    "background-color": "#E87722",
  },
  {
    School: "Providence",
    "City, State": "Providence, Rhode Island",
    "SR key": "providence",
    "NCAA key": "providence",
    "NCAA School": "Providence",
    "NCAA Name": "Providence College",
    "background-color": "#010101",
  },
  {
    School: "Purdue",
    "City, State": "West Lafayette, Indiana",
    "SR key": "purdue",
    "NCAA key": "purdue",
    "NCAA School": "Purdue",
    "NCAA Name": "Purdue University",
    "background-color": "#010101",
  },
  {
    School: "Purdue Fort Wayne",
    "City, State": "Fort Wayne, Indiana",
    "SR key": "ipfw",
    "NCAA key": "ipfw",
    "NCAA School": "Purdue University Fort Wayne",
    "NCAA Name": "Purdue University Fort Wayne",
    "background-color": "#1f3d7c",
  },
  {
    School: "Queens (NC)",
    "City, State": "Charlotte, North Carolina",
    "SR key": "queens-nc",
    "NCAA key": "queens-nc",
    "NCAA School": "Queens (NC)",
    "NCAA Name": "Queens University of Charlotte",
    "background-color": "#041E42",
  },
  {
    School: "Quinnipiac",
    "City, State": "Hamden, Connecticut",
    "SR key": "quinnipiac",
    "NCAA key": "quinnipiac",
    "NCAA School": "Quinnipiac",
    "NCAA Name": "Quinnipiac University",
    "background-color": "#0C2340",
  },
  {
    School: "Radford",
    "City, State": "Radford, Virginia",
    "SR key": "radford",
    "NCAA key": "radford",
    "NCAA School": "Radford",
    "NCAA Name": "Radford University",
    "background-color": "#C8102E",
  },
  {
    School: "Rhode Island",
    "City, State": "Kingston, Rhode Island",
    "SR key": "rhode-island",
    "NCAA key": "rhode-island",
    "NCAA School": "Rhode Island",
    "NCAA Name": "University of Rhode Island",
    "background-color": "#041E42",
  },
  {
    School: "Rice",
    "City, State": "Houston, Texas",
    "SR key": "rice",
    "NCAA key": "rice",
    "NCAA School": "Rice",
    "NCAA Name": "Rice University",
    "background-color": "#00205B",
  },
  {
    School: "Richmond",
    "City, State": "Richmond, Virginia",
    "SR key": "richmond",
    "NCAA key": "richmond",
    "NCAA School": "Richmond",
    "NCAA Name": "University of Richmond",
    "background-color": "#BA0C2F",
  },
  {
    School: "Rider",
    "City, State": "Lawrenceville, New Jersey",
    "SR key": "rider",
    "NCAA key": "rider",
    "NCAA School": "Rider",
    "NCAA Name": "Rider University",
    "background-color": "#9D2235",
  },
  {
    School: "Robert Morris",
    "City, State": "Moon Township, Pennsylvania",
    "SR key": "robert-morris",
    "NCAA key": "robert-morris",
    "NCAA School": "Robert Morris",
    "NCAA Name": "Robert Morris University",
    "background-color": "#041E42",
  },
  {
    School: "Rutgers",
    "City, State": "New Brunswick, New Jersey",
    "SR key": "rutgers",
    "NCAA key": "rutgers",
    "NCAA School": "Rutgers",
    "NCAA Name": "Rutgers University",
    "background-color": "#C8102E",
  },
  {
    School: "Sacramento State",
    "City, State": "Sacramento, California",
    "SR key": "sacramento-state",
    "NCAA key": "sacramento-st",
    "NCAA School": "Sacramento St.",
    "NCAA Name": "Sacramento State University",
    "background-color": "#115740",
  },
  {
    School: "Sacred Heart",
    "City, State": "Fairfield, Connecticut",
    "SR key": "sacred-heart",
    "NCAA key": "sacred-heart",
    "NCAA School": "Sacred Heart",
    "NCAA Name": "Sacred Heart University",
    "background-color": "#BA0C2F",
  },
  {
    School: "Saint Francis (PA)",
    "City, State": "Loretto, Pennsylvania",
    "SR key": "saint-francis-pa",
    "NCAA key": "saint-francis-pa",
    "NCAA School": undefined,
    "NCAA Name": undefined,
    "background-color": undefined,
  },
  {
    School: "Saint Joseph's",
    "City, State": "Philadelphia, Pennsylvania",
    "SR key": "saint-josephs",
    "NCAA key": "saint-josephs",
    "NCAA School": "Saint Joseph's",
    "NCAA Name": "Saint Joseph's University",
    "background-color": "#9D2235",
  },
  {
    School: "Saint Louis",
    "City, State": "St. Louis, Missouri",
    "SR key": "saint-louis",
    "NCAA key": "saint-louis",
    "NCAA School": "St. Louis",
    "NCAA Name": "Saint Louis University",
    "background-color": "#003DA5",
  },
  {
    School: "Saint Mary's (CA)",
    "City, State": "Moraga, California",
    "SR key": "saint-marys-ca",
    "NCAA key": "st-marys-ca",
    "NCAA School": "Saint-Mary's (CA)",
    "NCAA Name": "St. Mary's College (CA)",
    "background-color": "#E51B24",
  },
  {
    School: "Saint Peter's",
    "City, State": "Jersey City, New Jersey",
    "SR key": "saint-peters",
    "NCAA key": "saint-peters",
    "NCAA School": "Saint Peter's",
    "NCAA Name": "Saint Peter's University",
    "background-color": undefined,
  },
  {
    School: "Sam Houston",
    "City, State": "Huntsville, Texas",
    "SR key": "sam-houston-state",
    "NCAA key": "sam-houston-st",
    "NCAA School": "Sam Houston St.",
    "NCAA Name": "Sam Houston State University",
    "background-color": "#DF502A",
  },
  {
    School: "Samford",
    "City, State": "Birmingham, Alabama",
    "SR key": "samford",
    "NCAA key": "samford",
    "NCAA School": "Samford",
    "NCAA Name": "Samford University",
    "background-color": "#0C2340",
  },
  {
    School: "San Diego",
    "City, State": "San Diego, California",
    "SR key": "san-diego",
    "NCAA key": "san-diego",
    "NCAA School": "San Diego",
    "NCAA Name": "University of San Diego",
    "background-color": "#00205B",
  },
  {
    School: "San Diego State",
    "City, State": "San Diego, California",
    "SR key": "san-diego-state",
    "NCAA key": "san-diego-st",
    "NCAA School": "San Diego St.",
    "NCAA Name": "San Diego State University",
    "background-color": "#A6192E",
  },
  {
    School: "San Francisco",
    "City, State": "San Francisco, California",
    "SR key": "san-francisco",
    "NCAA key": "san-francisco",
    "NCAA School": "San Francisco",
    "NCAA Name": "University of San Francisco",
    "background-color": "#205C40",
  },
  {
    School: "San Jose State",
    "City, State": "San Jose, California",
    "SR key": "san-jose-state",
    "NCAA key": "san-jose-st",
    "NCAA School": "San Jose St.",
    "NCAA Name": "San Jose State University",
    "background-color": "#233A82",
  },
  {
    School: "Santa Clara",
    "City, State": "Santa Clara, California",
    "SR key": "santa-clara",
    "NCAA key": "santa-clara",
    "NCAA School": "Santa Clara",
    "NCAA Name": "Santa Clara University",
    "background-color": "#862633",
  },
  {
    School: "Seattle",
    "City, State": "Seattle, Washington",
    "SR key": "seattle",
    "NCAA key": "seattle",
    "NCAA School": "Seattle",
    "NCAA Name": "Seattle University",
    "background-color": "#BA0C2F",
  },
  {
    School: "Seton Hall",
    "City, State": "South Orange, New Jersey",
    "SR key": "seton-hall",
    "NCAA key": "seton-hall",
    "NCAA School": "Seton Hall",
    "NCAA Name": "Seton Hall University",
    "background-color": "#1A5DAD",
  },
  {
    School: "Siena",
    "City, State": "Loudonville, New York",
    "SR key": "siena",
    "NCAA key": "siena",
    "NCAA School": "Siena",
    "NCAA Name": "Siena College",
    "background-color": "#006747",
  },
  {
    School: "South Alabama",
    "City, State": "Mobile, Alabama",
    "SR key": "south-alabama",
    "NCAA key": "south-ala",
    "NCAA School": "South Ala.",
    "NCAA Name": "University of South Alabama",
    "background-color": "#BF0D3E",
  },
  {
    School: "South Carolina",
    "City, State": "Columbia, South Carolina",
    "SR key": "south-carolina",
    "NCAA key": "south-carolina",
    "NCAA School": "South Carolina",
    "NCAA Name": "University of South Carolina",
    "background-color": "#862633",
  },
  {
    School: "South Carolina State",
    "City, State": "Orangeburg, South Carolina",
    "SR key": "south-carolina-state",
    "NCAA key": "south-carolina-st",
    "NCAA School": "South Carolina St.",
    "NCAA Name": "South Carolina State University",
    "background-color": "#862633",
  },
  {
    School: "South Carolina Upstate",
    "City, State": "Spartanburg, South Carolina",
    "SR key": "south-carolina-upstate",
    "NCAA key": "usc-upstate",
    "NCAA School": "South-Carolina-Upstate",
    "NCAA Name": "University of South Carolina Upstate",
    "background-color": "#046A38",
  },
  {
    School: "South Dakota",
    "City, State": "Vermillion, South Dakota",
    "SR key": "south-dakota",
    "NCAA key": "south-dakota",
    "NCAA School": "South Dakota",
    "NCAA Name": "University of South Dakota",
    "background-color": "#BA0C2F",
  },
  {
    School: "South Dakota State",
    "City, State": "Brookings, South Dakota",
    "SR key": "south-dakota-state",
    "NCAA key": "south-dakota-st",
    "NCAA School": "South Dakota St.",
    "NCAA Name": "South Dakota State University",
    "background-color": "#0032A0",
  },
  {
    School: "South Florida",
    "City, State": "Tampa, Florida",
    "SR key": "south-florida",
    "NCAA key": "south-fla",
    "NCAA School": "South Fla.",
    "NCAA Name": "University of South Florida",
    "background-color": "#006747",
  },
  {
    School: "Southeast Missouri State",
    "City, State": "Cape Girardeau, Missouri",
    "SR key": "southeast-missouri-state",
    "NCAA key": "southeast-mo-st",
    "NCAA School": "Southeast Mo. St.",
    "NCAA Name": "Southeast Missouri State University",
    "background-color": "#010101",
  },
  {
    School: "Southeastern Louisiana",
    "City, State": "Hammond, Louisiana",
    "SR key": "southeastern-louisiana",
    "NCAA key": "southeastern-la",
    "NCAA School": "Southeastern La.",
    "NCAA Name": "Southeastern Louisiana University",
    "background-color": "#1D4C30",
  },
  {
    School: "Southern",
    "City, State": "Baton Rouge, Louisiana",
    "SR key": "southern",
    "NCAA key": "southern-u",
    "NCAA School": "Southern U.",
    "NCAA Name": "Southern University",
    "background-color": "#69B3E7",
  },
  {
    School: "Southern California",
    "City, State": "Los Angeles, California",
    "SR key": "southern-california",
    "NCAA key": "southern-california",
    "NCAA School": "Southern California",
    "NCAA Name": "University of Southern California",
    "background-color": "#9D2235",
  },
  {
    School: "Southern Illinois",
    "City, State": "Carbondale, Illinois",
    "SR key": "southern-illinois",
    "NCAA key": "southern-ill",
    "NCAA School": "Southern Ill.",
    "NCAA Name": "Southern Illinois University",
    "background-color": "#6F263D",
  },
  {
    School: "Southern Illinois-Edwardsville",
    "City, State": "Edwardsville, Illinois",
    "SR key": "southern-illinois-edwardsville",
    "NCAA key": "siu-edwardsville",
    "NCAA School": "SIUE",
    "NCAA Name": "Southern Illinois Univ.-Edwardsville",
    "background-color": "#DB372F",
  },
  {
    School: "Southern Indiana",
    "City, State": "Evansville, Indiana",
    "SR key": "southern-indiana",
    "NCAA key": "southern-ind",
    "NCAA School": "Southern Ind.",
    "NCAA Name": "University of Southern Indiana",
    "background-color": "#002855",
  },
  {
    School: "Southern Methodist",
    "City, State": "Dallas, Texas",
    "SR key": "southern-methodist",
    "NCAA key": "smu",
    "NCAA School": "SMU",
    "NCAA Name": "Southern Methodist University",
    "background-color": "#C8102E",
  },
  {
    School: "Southern Mississippi",
    "City, State": "Hattiesburg, Mississippi",
    "SR key": "southern-mississippi",
    "NCAA key": "southern-miss",
    "NCAA School": "Southern Miss.",
    "NCAA Name": "The University of Southern Mississippi",
    "background-color": "#010101",
  },
  {
    School: "Southern Utah",
    "City, State": "Cedar City, Utah",
    "SR key": "southern-utah",
    "NCAA key": "southern-utah",
    "NCAA School": "Southern Utah",
    "NCAA Name": "Southern Utah University",
    "background-color": "#BA0C2F",
  },
  {
    School: "St. Bonaventure",
    "City, State": "St. Bonaventure, New York",
    "SR key": "st-bonaventure",
    "NCAA key": "st-bonaventure",
    "NCAA School": "St. Bonaventure",
    "NCAA Name": "St. Bonaventure University",
    "background-color": "#412E26",
  },
  {
    School: "St. John's (NY)",
    "City, State": "Queens, New York",
    "SR key": "st-johns-ny",
    "NCAA key": "st-johns-ny",
    "NCAA School": "St. John's (NY)",
    "NCAA Name": "St. John's University (N.Y.)",
    "background-color": "#BA0C2F",
  },
  {
    School: "St. Thomas",
    "City, State": "St. Paul, Minnesota",
    "SR key": "st-thomas-mn",
    "NCAA key": "st-thomas-mn",
    "NCAA School": "St. Thomas (MN)",
    "NCAA Name": "University of St. Thomas (Minn.)",
    "background-color": "#412784",
  },
  {
    School: "Stanford",
    "City, State": "Stanford, California",
    "SR key": "stanford",
    "NCAA key": "stanford",
    "NCAA School": "Stanford",
    "NCAA Name": "Stanford University",
    "background-color": "#9D2235",
  },
  {
    School: "Stephen F. Austin",
    "City, State": "Nacogdoches, Texas",
    "SR key": "stephen-f-austin",
    "NCAA key": "stephen-f-austin",
    "NCAA School": "Stephen F. Austin",
    "NCAA Name": "Stephen F. Austin State University",
    "background-color": "#532F7C",
  },
  {
    School: "Stetson",
    "City, State": "DeLand, Florida",
    "SR key": "stetson",
    "NCAA key": "stetson",
    "NCAA School": "Stetson",
    "NCAA Name": "Stetson University",
    "background-color": "#006747",
  },
  {
    School: "Stonehill",
    "City, State": "Easton, Massachusetts",
    "SR key": "stonehill",
    "NCAA key": "stonehill",
    "NCAA School": "Stonehill",
    "NCAA Name": "Stonehill College",
    "background-color": "#582C83",
  },
  {
    School: "Stony Brook",
    "City, State": "Stony Brook, New York",
    "SR key": "stony-brook",
    "NCAA key": "stony-brook",
    "NCAA School": "Stony Brook",
    "NCAA Name": "Stony Brook University",
    "background-color": "#A6192E",
  },
  {
    School: "Syracuse",
    "City, State": "Syracuse, New York",
    "SR key": "syracuse",
    "NCAA key": "syracuse",
    "NCAA School": "Syracuse",
    "NCAA Name": "Syracuse University",
    "background-color": "#DC4405",
  },
  {
    School: "Tarleton State",
    "City, State": "Stephenville, Texas",
    "SR key": "tarleton-state",
    "NCAA key": "tarleton-st",
    "NCAA School": "Tarleton St.",
    "NCAA Name": "Tarleton State University",
    "background-color": "#582C83",
  },
  {
    School: "TCU",
    "City, State": "Fort Worth, Texas",
    "SR key": "texas-christian",
    "NCAA key": "tcu",
    "NCAA School": "TCU",
    "NCAA Name": "Texas Christian University",
    "background-color": "#592D82",
  },
  {
    School: "Temple",
    "City, State": "Philadelphia, Pennsylvania",
    "SR key": "temple",
    "NCAA key": "temple",
    "NCAA School": "Temple",
    "NCAA Name": "Temple University",
    "background-color": "#b30838",
  },
  {
    School: "Tennessee",
    "City, State": "Knoxville, Tennessee",
    "SR key": "tennessee",
    "NCAA key": "tennessee",
    "NCAA School": "Tennessee",
    "NCAA Name": "University of Tennessee",
    "background-color": "#FF8200",
  },
  {
    School: "Tennessee State",
    "City, State": "Nashville, Tennessee",
    "SR key": "tennessee-state",
    "NCAA key": "tennessee-st",
    "NCAA School": "Tennessee St.",
    "NCAA Name": "Tennessee State University",
    "background-color": "#272E63",
  },
  {
    School: "Tennessee Tech",
    "City, State": "Cookeville, Tennessee",
    "SR key": "tennessee-tech",
    "NCAA key": "tennessee-tech",
    "NCAA School": "Tennessee Tech",
    "NCAA Name": "Tennessee Technological University",
    "background-color": "#753BBD",
  },
  {
    School: "Tennessee-Martin",
    "City, State": "Martin, Tennessee",
    "SR key": "tennessee-martin",
    "NCAA key": "ut-martin",
    "NCAA School": "Tenn-Martin",
    "NCAA Name": "University of Tennessee at Martin",
    "background-color": "#0C2340",
  },
  {
    School: "Texas",
    "City, State": "Austin, Texas",
    "SR key": "texas",
    "NCAA key": "texas",
    "NCAA School": "Texas",
    "NCAA Name": "University of Texas",
    "background-color": "#CB6015",
  },
  {
    School: "Texas A&M",
    "City, State": "College Station, Texas",
    "SR key": "texas-am",
    "NCAA key": "texas-am",
    "NCAA School": "Texas A&M",
    "NCAA Name": "Texas A&M University",
    "background-color": "#5D0025",
  },
  {
    School: "Texas A&M-Commerce",
    "City, State": "Commerce, Texas",
    "SR key": "texas-am-commerce",
    "NCAA key": "tex-am-commerce",
    "NCAA School": "Tex. A&M-Commerce",
    "NCAA Name": "Texas A&M-Commerce",
    "background-color": "#00205B",
  },
  {
    School: "Texas A&M-Corpus Christi",
    "City, State": "Corpus Christi, Texas",
    "SR key": "texas-am-corpus-christi",
    "NCAA key": "am-corpus-chris",
    "NCAA School": "Texas-Am-Corpus",
    "NCAA Name": "Texas A&M-Corpus Christi",
    "background-color": "#007AC1",
  },
  {
    School: "Texas Southern",
    "City, State": "Houston, Texas",
    "SR key": "texas-southern",
    "NCAA key": "texas-southern",
    "NCAA School": "Texas Southern",
    "NCAA Name": "Texas Southern University",
    "background-color": "#6F263D",
  },
  {
    School: "Texas State",
    "City, State": "San Marcos, Texas",
    "SR key": "texas-state",
    "NCAA key": "texas-st",
    "NCAA School": "Texas St.",
    "NCAA Name": "Texas State University",
    "background-color": "#572932",
  },
  {
    School: "Texas Tech",
    "City, State": "Lubbock, Texas",
    "SR key": "texas-tech",
    "NCAA key": "texas-tech",
    "NCAA School": "Texas Tech",
    "NCAA Name": "Texas Tech University",
    "background-color": "#ED1F2A",
  },
  {
    School: "Texas-Rio Grande Valley",
    "City, State": "Edinburg, Texas",
    "SR key": "texas-pan-american",
    "NCAA key": "utrgv",
    "NCAA School": "Texas Rio Grande Valley",
    "NCAA Name": "University of Texas Rio Grande Valley",
    "background-color": "#FF4D00",
  },
  {
    School: "The Citadel",
    "City, State": "Charleston, South Carolina",
    "SR key": "citadel",
    "NCAA key": "citadel",
    "NCAA School": "Citadel",
    "NCAA Name": "The Citadel",
    "background-color": "#77A5C3",
  },
  {
    School: "Toledo",
    "City, State": "Toledo, Ohio",
    "SR key": "toledo",
    "NCAA key": "toledo",
    "NCAA School": "Toledo",
    "NCAA Name": "University of Toledo",
    "background-color": "#00205B",
  },
  {
    School: "Towson",
    "City, State": "Towson, Maryland",
    "SR key": "towson",
    "NCAA key": "towson",
    "NCAA School": "Towson",
    "NCAA Name": "Towson University",
    "background-color": "#010101",
  },
  {
    School: "Troy",
    "City, State": "Troy, Alabama",
    "SR key": "troy",
    "NCAA key": "troy",
    "NCAA School": "Troy",
    "NCAA Name": "Troy University",
    "background-color": "#9D2235",
  },
  {
    School: "Tulane",
    "City, State": "New Orleans, Louisiana",
    "SR key": "tulane",
    "NCAA key": "tulane",
    "NCAA School": "Tulane",
    "NCAA Name": "Tulane University",
    "background-color": "#006747",
  },
  {
    School: "Tulsa",
    "City, State": "Tulsa, Oklahoma",
    "SR key": "tulsa",
    "NCAA key": "tulsa",
    "NCAA School": "Tulsa",
    "NCAA Name": "The University of Tulsa",
    "background-color": "#002D72",
  },
  {
    School: "UAB",
    "City, State": "Birmingham, Alabama",
    "SR key": "alabama-birmingham",
    "NCAA key": "uab",
    "NCAA School": "UAB",
    "NCAA Name": "UAB",
    "background-color": "#006341",
  },
  {
    School: "UC Davis",
    "City, State": "Davis, California",
    "SR key": "california-davis",
    "NCAA key": "uc-davis",
    "NCAA School": "UC Davis",
    "NCAA Name": "UC Davis",
    "background-color": "#002855",
  },
  {
    School: "UC Irvine",
    "City, State": "Irvine, California",
    "SR key": "california-irvine",
    "NCAA key": "uc-irvine",
    "NCAA School": "UC Irvine",
    "NCAA Name": "UC Irvine",
    "background-color": "#0C2340",
  },
  {
    School: "UC Riverside",
    "City, State": "Riverside, California",
    "SR key": "california-riverside",
    "NCAA key": "uc-riverside",
    "NCAA School": "UC Riverside",
    "NCAA Name": "UC Riverside",
    "background-color": "#1E437B",
  },
  {
    School: "UC San Diego",
    "City, State": "La Jolla, California",
    "SR key": "california-san-diego",
    "NCAA key": "uc-san-diego",
    "NCAA School": "UC San Diego",
    "NCAA Name": "UC San Diego",
    "background-color": "#192847",
  },
  {
    School: "UC Santa Barbara",
    "City, State": "Santa Barbara, California",
    "SR key": "california-santa-barbara",
    "NCAA key": "uc-santa-barbara",
    "NCAA School": "UC Santa Barbara",
    "NCAA Name": "UC Santa Barbara",
    "background-color": "#0032A0",
  },
  {
    School: "UCLA",
    "City, State": "Los Angeles, California",
    "SR key": "ucla",
    "NCAA key": "ucla",
    "NCAA School": "UCLA",
    "NCAA Name": "UCLA",
    "background-color": "#0072CE",
  },
  {
    School: "UNC Asheville",
    "City, State": "Asheville, North Carolina",
    "SR key": "north-carolina-asheville",
    "NCAA key": "unc-asheville",
    "NCAA School": "UNC Asheville",
    "NCAA Name": "UNC Asheville",
    "background-color": "#002F6C",
  },
  {
    School: "UNC Greensboro",
    "City, State": "Greensboro, North Carolina",
    "SR key": "north-carolina-greensboro",
    "NCAA key": "unc-greensboro",
    "NCAA School": "UNC Greensboro",
    "NCAA Name": "UNC Greensboro",
    "background-color": "#13294B",
  },
  {
    School: "UNC Wilmington",
    "City, State": "Wilmington, North Carolina",
    "SR key": "north-carolina-wilmington",
    "NCAA key": "unc-wilmington",
    "NCAA School": "UNCW",
    "NCAA Name": "UNC Wilmington",
    "background-color": "#00685E",
  },
  {
    School: "UT Arlington",
    "City, State": "Arlington, Texas",
    "SR key": "texas-arlington",
    "NCAA key": "texas-arlington",
    "NCAA School": "Texas at Arlington",
    "NCAA Name": "University of Texas at Arlington",
    "background-color": "#003DA5",
  },
  {
    School: "Utah",
    "City, State": "Salt Lake City, Utah",
    "SR key": "utah",
    "NCAA key": "utah",
    "NCAA School": "Utah",
    "NCAA Name": "University of Utah",
    "background-color": "#D42331",
  },
  {
    School: "Utah State",
    "City, State": "Logan, Utah",
    "SR key": "utah-state",
    "NCAA key": "utah-st",
    "NCAA School": "Utah St.",
    "NCAA Name": "Utah State University",
    "background-color": "#00263A",
  },
  {
    School: "Utah Tech",
    "City, State": "St. George, Utah",
    "SR key": "dixie-state",
    "NCAA key": "utah-tech",
    "NCAA School": "Utah Tech",
    "NCAA Name": "Utah Tech University",
    "background-color": "#BA1C21",
  },
  {
    School: "Utah Valley",
    "City, State": "Orem, Utah",
    "SR key": "utah-valley",
    "NCAA key": "utah-valley",
    "NCAA School": "Utah Valley",
    "NCAA Name": "Utah Valley University",
    "background-color": "#275D38",
  },
  {
    School: "UTEP",
    "City, State": "El Paso, Texas",
    "SR key": "texas-el-paso",
    "NCAA key": "utep",
    "NCAA School": "Texas at El Paso",
    "NCAA Name": "University of Texas at El Paso",
    "background-color": "#041E42",
  },
  {
    School: "UTSA",
    "City, State": "San Antonio, Texas",
    "SR key": "texas-san-antonio",
    "NCAA key": "utsa",
    "NCAA School": "Texas at San Antonio",
    "NCAA Name": "University of Texas at San Antonio",
    "background-color": "#0C2340",
  },
  {
    School: "Valparaiso",
    "City, State": "Valparaiso, Indiana",
    "SR key": "valparaiso",
    "NCAA key": "valparaiso",
    "NCAA School": "Valparaiso",
    "NCAA Name": "Valparaiso University",
    "background-color": "#693F23",
  },
  {
    School: "Vanderbilt",
    "City, State": "Nashville, Tennessee",
    "SR key": "vanderbilt",
    "NCAA key": "vanderbilt",
    "NCAA School": "Vanderbilt",
    "NCAA Name": "Vanderbilt University",
    "background-color": "#010101",
  },
  {
    School: "Vermont",
    "City, State": "Burlington, Vermont",
    "SR key": "vermont",
    "NCAA key": "vermont",
    "NCAA School": "Vermont",
    "NCAA Name": "University of Vermont",
    "background-color": "#154734",
  },
  {
    School: "Villanova",
    "City, State": "Villanova, Pennsylvania",
    "SR key": "villanova",
    "NCAA key": "villanova",
    "NCAA School": "Villanova",
    "NCAA Name": "Villanova University",
    "background-color": "#173A79",
  },
  {
    School: "Virginia",
    "City, State": "Charlottesville, Virginia",
    "SR key": "virginia",
    "NCAA key": "virginia",
    "NCAA School": "Virginia",
    "NCAA Name": "University of Virginia",
    "background-color": "#232D4B",
  },
  {
    School: "Virginia Commonwealth",
    "City, State": "Richmond, Virginia",
    "SR key": "virginia-commonwealth",
    "NCAA key": "vcu",
    "NCAA School": "VCU",
    "NCAA Name": "Virginia Commonwealth University",
    "background-color": "#010101",
  },
  {
    School: "Virginia Military Institute",
    "City, State": "Lexington, Virginia",
    "SR key": "virginia-military-institute",
    "NCAA key": "vmi",
    "NCAA School": "VMI",
    "NCAA Name": "Virginia Military Institute",
    "background-color": "#E4002B",
  },
  {
    School: "Virginia Tech",
    "City, State": "Blacksburg, Virginia",
    "SR key": "virginia-tech",
    "NCAA key": "virginia-tech",
    "NCAA School": "Virginia Tech",
    "NCAA Name": "Virginia Tech",
    "background-color": "#861F41",
  },
  {
    School: "Wagner",
    "City, State": "Staten Island, New York",
    "SR key": "wagner",
    "NCAA key": "wagner",
    "NCAA School": "Wagner",
    "NCAA Name": "Wagner College",
    "background-color": "#034638",
  },
  {
    School: "Wake Forest",
    "City, State": "Winston-Salem, North Carolina",
    "SR key": "wake-forest",
    "NCAA key": "wake-forest",
    "NCAA School": "Wake Forest",
    "NCAA Name": "Wake Forest University",
    "background-color": "#010101",
  },
  {
    School: "Washington",
    "City, State": "Seattle, Washington",
    "SR key": "washington",
    "NCAA key": "washington",
    "NCAA School": "Washington",
    "NCAA Name": "University of Washington",
    "background-color": "#33006f",
  },
  {
    School: "Washington State",
    "City, State": "Pullman, Washington",
    "SR key": "washington-state",
    "NCAA key": "washington-st",
    "NCAA School": "Washington St.",
    "NCAA Name": "Washington State University",
    "background-color": "#9D2235",
  },
  {
    School: "Weber State",
    "City, State": "Ogden, Utah",
    "SR key": "weber-state",
    "NCAA key": "weber-st",
    "NCAA School": "Weber St.",
    "NCAA Name": "Weber State University",
    "background-color": "#470A68",
  },
  {
    School: "West Virginia",
    "City, State": "Morgantown, West Virginia",
    "SR key": "west-virginia",
    "NCAA key": "west-virginia",
    "NCAA School": "West Virginia",
    "NCAA Name": "West Virginia University",
    "background-color": "#0F2D52",
  },
  {
    School: "Western Carolina",
    "City, State": "Cullowhee, North Carolina",
    "SR key": "western-carolina",
    "NCAA key": "western-caro",
    "NCAA School": "Western Caro.",
    "NCAA Name": "Western Carolina University",
    "background-color": "#5F259F",
  },
  {
    School: "Western Illinois",
    "City, State": "Macomb, Illinois",
    "SR key": "western-illinois",
    "NCAA key": "western-ill",
    "NCAA School": "Western Ill.",
    "NCAA Name": "Western Illinois University",
    "background-color": "#59327E",
  },
  {
    School: "Western Kentucky",
    "City, State": "Bowling Green, Kentucky",
    "SR key": "western-kentucky",
    "NCAA key": "western-ky",
    "NCAA School": "Western Ky.",
    "NCAA Name": "Western Kentucky University",
    "background-color": "#C8102E",
  },
  {
    School: "Western Michigan",
    "City, State": "Kalamazoo, Michigan",
    "SR key": "western-michigan",
    "NCAA key": "western-mich",
    "NCAA School": "Western Mich.",
    "NCAA Name": "Western Michigan University",
    "background-color": "#511B00",
  },
  {
    School: "Wichita State",
    "City, State": "Wichita, Kansas",
    "SR key": "wichita-state",
    "NCAA key": "wichita-st",
    "NCAA School": "Wichita St.",
    "NCAA Name": "Wichita State University",
    "background-color": "#010101",
  },
  {
    School: "William & Mary",
    "City, State": "Williamsburg, Virginia",
    "SR key": "william-mary",
    "NCAA key": "william-mary",
    "NCAA School": "William & Mary",
    "NCAA Name": "College of William and Mary",
    "background-color": "#284734",
  },
  {
    School: "Winthrop",
    "City, State": "Rock Hill, South Carolina",
    "SR key": "winthrop",
    "NCAA key": "winthrop",
    "NCAA School": "Winthrop",
    "NCAA Name": "Winthrop University",
    "background-color": "#9D2235",
  },
  {
    School: "Wisconsin",
    "City, State": "Madison, Wisconsin",
    "SR key": "wisconsin",
    "NCAA key": "wisconsin",
    "NCAA School": "Wisconsin",
    "NCAA Name": "University of Wisconsin, Madison",
    "background-color": "#BA0C2F",
  },
  {
    School: "Wofford",
    "City, State": "Spartanburg, South Carolina",
    "SR key": "wofford",
    "NCAA key": "wofford",
    "NCAA School": "Wofford",
    "NCAA Name": "Wofford College",
    "background-color": "#8A6E4B",
  },
  {
    School: "Wright State",
    "City, State": "Dayton, Ohio",
    "SR key": "wright-state",
    "NCAA key": "wright-st",
    "NCAA School": "Wright St.",
    "NCAA Name": "Wright State University",
    "background-color": "#046A38",
  },
  {
    School: "Wyoming",
    "City, State": "Laramie, Wyoming",
    "SR key": "wyoming",
    "NCAA key": "wyoming",
    "NCAA School": "Wyoming",
    "NCAA Name": "University of Wyoming",
    "background-color": "#4E3629",
  },
  {
    School: "Xavier",
    "City, State": "Cincinnati, Ohio",
    "SR key": "xavier",
    "NCAA key": "xavier",
    "NCAA School": "Xavier",
    "NCAA Name": "Xavier University",
    "background-color": "#0C2340",
  },
  {
    School: "Yale",
    "City, State": "New Haven, Connecticut",
    "SR key": "yale",
    "NCAA key": "yale",
    "NCAA School": "Yale",
    "NCAA Name": "Yale University",
    "background-color": "#111C2C",
  },
  {
    School: "Youngstown State",
    "City, State": "Youngstown, Ohio",
    "SR key": "youngstown-state",
    "NCAA key": "youngstown-st",
    "NCAA School": "Youngstown St.",
    "NCAA Name": "Youngstown State University",
    "background-color": "#C8102E",
  },
];
